version: "3.9"
name: solution

services:
  # api_server:
    # build: .
    # container_name: solution-api
    # ports:
    #   - 3333:3333
    # volumes:
    #   - ./:/usr/src/omnichannel
    # links:
    #   - "db"
    #   - "db_test"

  db:
    container_name: solution-db
    profiles:
      - dev
    build: .docker/postgres
    # restart: always
    # tty: true
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/pgdata:/var/lib/postgresql/data/pgdata
    security_opt:
      - seccomp:unconfined
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
      PGDATA: /tmp
    command: >
      bash -c "echo 'max_connections=100' >> /var/lib/postgresql/data/pgdata/postgresql.conf && docker-entrypoint.sh postgres"

  rabbit:
    build:
      context: .docker/rabbitmq
      dockerfile: Dockerfile
    profiles:
      - dev
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbitmq_stream advertised_host localhost
    ports:
      - "15672:15672"
      - "5672:5672"
      - "5551:5551"
      - "5552:5552"

   

